# Default playbook.
#
# Should configure a development setup to the point where a server or
# equivalent can be started with a single command.
---
# Run the entire common setup playbook
- include: common.yml

- hosts: all

  become: true
  become_method: sudo
  become_user: root

...
